# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: chuchard <chuchard@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 17:29:03 by chuchard          #+#    #+#              #
#    Updated: 2024/02/12 19:40:38 by chuchard         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = philo

FLAGS

RM = rm -rf

SRCS

$(NAME) :
	gcc $(FLAGS) $(SRCS) -o $(NAME)

all : $(NAME)

fclean : clean


clean :
	$(RM) $(NAME)

re : fclean all